### ISSUE TITLE
Los Insertos al ser un videojuego no son necesario, si acaso se podría añadir un tablero propio del jugador. También es innecesario la bolsita si se pone el tablero de recursos del jugador mencionado.

### ISSUE THREAD

**Issue by AdrianNYV** [SoniaPria/p2_dxpp#2]
Los Insertos al ser un videojuego no son necesario, si acaso se podría añadir un tablero propio del jugador. También es innecesario la bolsita si se pone el tablero de recursos del jugador mencionado.

_Originally posted by @AdrianNYV in https://github.com/SoniaPria/p2_dxpp/pull/1#discussion_r1104774691_

**Comment by SoniaPria** [comment]
Ok. Se tratan como shockets
